"""Remove ip_address and make name unique

Revision ID: 93fcc700cbaf
Revises: 972a56abcb79
Create Date: 2025-11-20 02:02:59.952738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93fcc700cbaf'
down_revision = '972a56abcb79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.VARCHAR(length=45), nullable=False))
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
